server.port=8080

jdbc.url=jdbc:postgresql://localhost:5432/*your_user*
jdbc.user=your_user
jdbc.password=your_password
jdbc.poolSize=8

jwt.secret=replace-this-secret-with-long-random-string
jwt.ttl.minutes=60

otp.expiration.scan.seconds=30
otp.file.path=otp-output.txt
